# Generated by Django 3.0.5 on 2020-04-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200417_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
    ]
