# Generated by Django 3.0.5 on 2020-04-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_count_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_sells',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
