# Generated by Django 3.0.5 on 2020-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=120)),
                ('image_alt', models.TextField(blank=True, null=True)),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
